# AUTOGENERATED! DO NOT EDIT! File to edit: ../Example_catsVSdogs.ipynb.
import pathlib
pathlib.WindowsPath = pathlib.PosixPath

# %% auto 0
__all__ = ['is_cat', 'learn', 'classify_image', 'categories', 'image', 'label', 'examples', 'intf']

## %% ../Example_catsVSdogs.ipynb 13
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

## %% ../Example_catsVSdogs.ipynb 15
learn = load_learner('model_catsVSdogs.pkl')

# %% ../Example_catsVSdogs.ipynb 17
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% ../Example_catsVSdogs.ipynb 20
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
